# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2024.

[package]
name = "cortexv7m"
version.workspace = true
authors.workspace = true
edition.workspace = true

[package.metadata.flux]
default_trusted = true
enabled = true
check_overflow = "lazy"

[dependencies]
kernel = { path = "../../kernel" }
flux-rs = { path = "../../flux/lib/flux-rs" }
flux_support = { path = "../../flux_support" }

[lints]
workspace = true
